# Programming Assignment 6
---
**Author:** Haziq Zed 
**Version:** 1.0  
**Semester:** Fall 2020  

This *notebook* contains my solution to **Programming Assignment 6**

- Problem a.

In [8]:
import numpy as np

d = np.array([[10,20],[30,40]])

array([[110, 120],
       [130, 140]])

In [9]:
d**2

array([[ 100,  400],
       [ 900, 1600]])

In [10]:
d+100

array([[110, 120],
       [130, 140]])

In [11]:
d*5

array([[ 50, 100],
       [150, 200]])

In [14]:
np.sqrt(d)

array([[3.16227766, 4.47213595],
       [5.47722558, 6.32455532]])

- Problem b.

In [24]:
d1 = np.array([[3,6,9],[12,15,18],[21,24,27]])
d2 = np.array([[11,12,13],[14,15,16],[17,18,19]])

d1*d2

array([[ 33,  72, 117],
       [168, 225, 288],
       [357, 432, 513]])

- Problem c.

In [48]:
n1 = np.load('process1.npy')
n2 = np.load('process2.npy')
n3 = np.load('process3.npy')
n4 = np.load('process4.npy')
n5 = np.load('process5.npy')

d3 = np.vstack((n1,n2,n3,n4,n5))
c1,c2,c3,c4,c5 = np.hsplit(d3,5)

print(f'Column 1 mean = {c1.mean()}')
print(f'Column 2 mean = {c2.mean()}')
print(f'Column 3 mean = {c3.mean()}')
print(f'Column 4 mean = {c4.mean()}')
print(f'Column 5 mean = {c5.mean()}')

Column 1 mean = 72.0
Column 2 mean = 27.8
Column 3 mean = 45.6
Column 4 mean = 12.0
Column 5 mean = 47.8


array([[52, 12, 81,  0, 58],
       [96,  4, 61, 16, 43],
       [38, 96, 45, 17, 58],
       [97, 21, 22, 25,  6],
       [77,  6, 19,  2, 74]], dtype=int32)